export const HF_INFERENCE_API_BASE_URL = process.env.HF_INFERENCE_API_BASE_URL;
export const HF_INFERENCE_API_KEY = process.env.HF_INFERENCE_API_KEY;
export const NEXT_PUBLIC_SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
